# Generated by Django 3.0.8 on 2020-07-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auctionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_to_auction',
            field=models.BooleanField(default=False),
        ),
    ]
