# Generated by Django 3.0.8 on 2020-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_product_added_to_auction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionproduct',
            options={'ordering': ['-id'], 'verbose_name_plural': '5.Auction Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
    ]
