# Generated by Django 3.0.8 on 2020-07-26 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0006_auctionbidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbidding',
            name='winner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
