# Generated by Django 3.0.8 on 2020-07-26 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0007_auto_20200726_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbidding',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionbidding',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
