# Generated by Django 3.0.8 on 2020-07-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20200726_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionbidding',
            name='winner',
        ),
    ]
