# Generated by Django 3.0.8 on 2020-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_auctionbidding_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbidding',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
