# Generated by Django 3.0.8 on 2020-07-31 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0011_auctionwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionwinner',
            name='is_complted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionwinner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
