# Generated by Django 3.0.8 on 2020-08-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionbidding',
            options={'verbose_name_plural': '6.AuctionBidding'},
        ),
        migrations.AlterModelOptions(
            name='auctionwinner',
            options={'verbose_name_plural': '7.AuctionWinner'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name_plural': '8.SearchHistory'},
        ),
    ]
